day5/day5/urls.py
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^st/',include('stu.urls',namespace='s')),
    url(r'^uau/',include('uauth.urls')),
]

from day5 import settings
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

day5/stu/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from stu import views

from rest_framework.routers import SimpleRouter

router = SimpleRouter()
router.register(r'student', views.Aba)

urlpatterns = [
    url(r'^index/', views.index),
    url(r'^add/', login_required(views.addStu), name='add'),
    url(r'^addinf/(?P<stu>\d+)', views.addStuInfo, name='addin'),
    url(r'^pag/', views.stuPage)

]

urlpatterns += router.urls

day5/uauth/urls.py
from django.conf.urls import url
from uauth import views

urlpatterns = [
    url(r'^re/', views.regist),
    url(r'^lo/', views.login),
    url(r'^out/', views.logout),
    url(r'djlo/', views.djlogin),
    url(r'djre/', views.djregist),
    url(r'djout/', views.djout),
]

day5/stu/models.py
from django.db import models


class Student(models.Model):
    s_name = models.CharField(max_length=10)
    s_tel = models.CharField(max_length=11)

    class Meta:
        db_table = 'day5_stu'


class StudentInfo(models.Model):
    i_addr = models.CharField(max_length=30)
    s = models.OneToOneField(Student)
    i_image = models.ImageField(upload_to='upload',null=True)

    class Meta:
        db_table = 'day5_stuinfo'


class Visit(models.Model):

    v_url = models.CharField(max_length=30)
    v_time = models.IntegerField()

    class Meta:
        db_table = 'visit'

day5/uauth/models.py
from django.db import models


# Create your models here.
class Users(models.Model):
    u_name = models.CharField(max_length=10)
    u_password = models.CharField(max_length=225)
    # 存在服务器中的cookie的值
    u_ticket = models.CharField(max_length=30, null=True)

    class Meta:
        db_table = 'day51_uesr'

day5/stu/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from stu.models import Student, StudentInfo
from stu.serializers import StudentSerializer
from uauth.models import Users
import logging

from rest_framework import mixins, viewsets

logger = logging.getLogger('stu')


def index(requset):
    if requset.method == 'GET':
        # # 获取cookie的值中的ticket值
        # t = requset.COOKIES.get('ticket')
        # if not t:
        #     return HttpResponseRedirect('/uau/lo/')
        # if Users.objects.filter(u_ticket=t).exists():
        #     #获取所有信息
        #     stuinfo = StudentInfo.objects.all()
        #     return render(requset, 'index.html',{'stuinfo':stuinfo})
        # else:
        #     return HttpResponseRedirect('/uau/lo/')

        stuinfo = StudentInfo.objects.all()
        logger.info('url:%s method:%s 获取学生信息成功' % (requset.path, requset.method))
        return render(requset, 'index.html', {'stuinfo': stuinfo})


def addStu(request):
    if request.method == 'GET':
        return render(request, 'add.html')

    if request.method == 'POST':
        # 跳转详情
        name = request.POST.get('name')
        tel = request.POST.get('tel')

        stu = Student.objects.create(
            s_name=name,
            s_tel=tel
        )
        # 传递参数 kwargs位置
        return HttpResponseRedirect(
            reverse('s:addin', kwargs={'stu': stu.id})
        )


def addStuInfo(request, stu):
    if request.method == 'GET':
        # 获取
        return render(request, 'addStu.html')

    if request.method == 'POST':
        # stu_id = request.POST.get('stu')
        addr = request.POST.get('addr')
        # 添加头像
        img = request.FILES.get('img')

        StudentInfo.objects.create(i_addr=addr, s_id=stu, i_image=img)
        # 不加reverse
        return HttpResponseRedirect(
            '/st/index/'
        )


def stuPage(request):
    if request.method == 'GET':
        # 获取参数如果为空就是1 表示首页
        pag = int(request.GET.get('page_id', 1))
        stu = StudentInfo.objects.all()
        pagina = Paginator(stu, 3)
        pagee = pagina.page(pag)

        return render(request, 'index_page.html', {'stu': pagee})


class Aba(mixins.ListModelMixin,
          mixins.RetrieveModelMixin,
          mixins.UpdateModelMixin,
          mixins.DestroyModelMixin,
          mixins.CreateModelMixin,
          viewsets.GenericViewSet):
    # 查询所有信息
    queryset = Student.objects.all()
    # 序列化
    serializer_class = StudentSerializer

day5/uauth/views.py
import random
import time

from django.contrib import auth
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from uauth.models import Users


def regist(request):
    if request.method == 'GET':
        return render(request, 'register.html')

    if request.method == 'POST':
        # 获取注册信息
        name = request.POST.get('name')
        pa = request.POST.get('password')
        if Users.objects.filter(u_name=name).exists():
            return render(request, 'register.html', {'name': '用户存在'})
        else:
            password = make_password(pa)
            Users.objects.create(
                u_name=name,
                u_password=password
            )
            return HttpResponseRedirect('/uau/lo/')


def login(request):
    if request.method == 'GET':
        return render(request, 'day6_login.html')

    if request.method == 'POST':
        # 登陆成功，绑定参数到coolie中 set_cookie
        name = request.POST.get('name')
        pa = request.POST.get('password')

        if Users.objects.filter(u_name=name).exists():
            uname = Users.objects.get(u_name=name)
            if check_password(pa, uname.u_password):
                ticket = ''
                for _ in range(15):
                    s = 'abcdefghijklmnopqrstuvwxyz'
                    # 获取随机字符串
                    ticket += random.choice(s)
                now_time = int(time.time())
                ticket = ticket + str(now_time)
                # 绑定令牌到coolie（浏览器）
                reponse = HttpResponseRedirect('/st/index/')
                # max_age表示存在时间——秒
                reponse.set_cookie('ticket', ticket, max_age=30000)
                # 存服务器中
                uname.u_ticket = ticket
                uname.save()
                return reponse  # 存在浏览器中  后面才能直接get到
            else:
                # return HttpResponse('密码错误')
                return render(request, 'day6_login.html', {'password': '密码错误'})
        else:
            # return HttpResponse('不存在')
            return render(request, 'day6_login.html', {'name': '用户名不存在'})


# 删除ticket返回登录页面（退出登录）
def logout(request):
    if request.method == 'GET':
        reponse = HttpResponseRedirect('/uau/lo/')
        reponse.delete_cookie('ticket')
        return reponse


# 自带的验证方式
def djlogin(request):
    if request.method == 'GET':
        return render(request, 'longin.html')

    if request.method == 'POST':
        name = request.POST.get('name')
        password = request.POST.get('password')
        # 验证用户密码和账户，通过的话返回user对象
        u = auth.authenticate(username=name, password=password)
        if u:
            # 验证成功
            auth.login(request, u)
            return HttpResponseRedirect('/st/index/')
        else:
            return render(request, 'longin.html')


# 注册
def djregist(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    if request.method == 'POST':
        name = request.POST.get('name')
        password = request.POST.get('password')

        User.objects.create_user(username=name, password=password)

        return HttpResponseRedirect('/uau/djlo/')


# 退出
def djout(request):
    if request.method == 'GET':
        auth.logout(request)
        return HttpResponseRedirect('/uau/djlo/')

day5/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>姓名</td>
            <td>电话</td>
        </tr>
        <tr>
            <td><input type="text" name="name"></td>
            <td><input type="text" name="tel"></td>
        </tr>
        <tr>
            <td><input type="submit" value="提交"></td>
        </tr>
    </table>

</form>
</body>
</html>

day5/templates/addStu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
<input type="hidden" value="{{ stu }}" name="stu">{#隐藏参数#}
    <table>
        <tr>
            <td>地址</td>
            <td>头像</td>
        </tr>
        <tr>
            <td><input type="text" name="addr"></td>
            <td><input type="file" name="img"></td>
        </tr>
    </table>
    <input type="submit" value="提交">
</form>
</body>
</html>

day5/templates/day6_login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0"> 
	<title>登录界面</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css" />
	<!--必要样式-->
    <link href="/static/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/demo.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/loaders.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

	<script type="text/javascript">
		function login(){
			err_name = $('#err_name').val()
			err_password = $('#err_password').val()
			if(err_name){
				alert(err_name)
			}else if(err_password){
				alert(err_password)
			}
		}
	</script>

</head>
<body onload="login()">
	<div class='login'>
	  <div class='login_title'>
	    <span>管理员登录</span>
	  </div>
		<input type="hidden" id="err_name" value="{{name}}"/>
		<input type="hidden" id="err_password" value="{{password}}"/>
		<form action="" method="post">
            {% csrf_token %}
	  <div class='login_fields'>
	    <div class='login_fields__user'>
	      <div class='icon'>
	        <img alt="" src='/static/img/user_icon_copy.png'>
	      </div>
	      <input name="name" placeholder='用户名' maxlength="16" type='text' autocomplete="off" value=""/>
	        <div class='validation'>
	          <img alt="" src='/static/img/tick.png'>
	        </div>
	    </div>
	    <div class='login_fields__password'>
	      <div class='icon'>
	        <img alt="" src='/static/img/lock_icon_copy.png'>
	      </div>
	      <input name="password" placeholder='密码' maxlength="16" type='text' autocomplete="off">
	      <div class='validation'>
	        <img alt="" src='/static/img/tick.png'>
	      </div>
	    </div>
	    <div class='login_fields__submit'>
	      	<input type='submit' value='登录'>
            <a href="/uau/re/">注册</a>
	    </div>
	  </div>
		</form>
	  <div class='success'>
	  </div>
	  <div class='disclaimer'>
	    <p>欢迎登录后台管理系统</p>
	  </div>
	</div>
	<div class='authent'>
	  <div class="loader" style="height: 44px;width: 44px;margin-left: 28px;">
        <div class="loader-inner ball-clip-rotate-multiple">
            <div></div>
            <div></div>
            <div></div>
        </div>
        </div>
	  <p>认证中...</p>
	</div>
	<div class="OverWindows"></div>
	
    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css" />
	
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src='/static/js/stopExecutionOnTimeout.js?t=1'></script>
    <script type="text/javascript" src="/static/layui/layui.js"></script>
    <script type="text/javascript" src="/static/js/Particleground.js"></script>
    <script type="text/javascript" src="/static/js/Treatment.js"></script>
    <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>

</body>
</html>

day5/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in stuinfo %}
    姓名：{{ i.s.s_name }}
    电话：{{ i.s.s_tel }}
    地址:{{ i.i_addr }}
    {% if i.i_image %}
    头像：
    <img src="/media/{{ i.i_image }}" height="100px" width="100px">
    {% endif %}
    <br>
{% endfor %}
<h4>-------------------------------------------</h4>
<a href="{% url 's:add'  %}">添加学生</a>
<a href="/uau/out/">退出登录</a>
<a href="/uau/djout/">管理员退出登录</a>
</body>
</html>

day5/templates/index_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in stu %}
    姓名：{{ i.s.s_name }}
    电话：{{ i.s.s_tel }}
    地址:{{ i.i_addr }}
    {% if i.i_image %}
    头像：
    <img src="/media/{{ i.i_image }}" height="100px" width="100px">
    {% endif %}
    <br>
{% endfor %}
<h4>一共{{ stu.paginator.num_pages }}页 {{ stu.paginator.count }}条信息</h4>
{%  for a in stu.paginator.page_range %}
    <a href="/st/pag/?page_id={{ a }}">{{ a }}</a>
{% endfor %}
{% if stu.has_previous %}
    <a href="/st/pag/?page_id={{ stu.previous_page_number }}">上一页</a>
{% endif %}
当前第{{ stu.number }}页
{% if stu.has_next %}
    <a href="/st/pag/?page_id={{ stu.next_page_number }}">下一页</a>
{% endif %}

<h4>-------------------------------------------</h4>
<a href="{% url 's:add'  %}">添加学生</a>
<a href="/uau/out/">退出登录</a>
</body>
</html>

day5/templates/longin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    登录姓名：<input type="text" name="name" required>
    密码：<input type="password" name="password" required>
    <input type="submit" value="确认登录">
</form>
<a href="/uau/re/">注册帐号</a>
</body>
</html>

day5/templates/register.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>注册</title>#}
{#</head>#}
{#<body>#}
{#<form action="" method="post">#}
{#    注册姓名：<input type="text" name="name" required>#}
{#    密码：<input type="password" name="password" required>#}
{#    <input type="submit" value="提交">#}
{#</form>#}
{#</body>#}
{#</html>#}


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">
	<title>注册界面</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css" />
	<!--必要样式-->
    <link href="/static/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/demo.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/loaders.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

	<script type="text/javascript">
		function login(){
			err_name = $('#err_name').val()
			err_password = $('#err_password').val()
			if(err_name){
				alert(err_name)
			}else if(err_password){
				alert(err_password)
			}
		}
	</script>

</head>
<body onload="login()">
	<div class='login'>
	  <div class='login_title'>
	    <span>注册帐号</span>
	  </div>
        <input type="hidden" id="err_name" value="{{name}}"/>
		<input type="hidden" id="err_password" value="{{password}}"/>
		<form action="" method="post">
            {% csrf_token %}
	  <div class='login_fields'>
	    <div class='login_fields__user'>
	      <div class='icon'>
	        <img alt="" src='/static/img/user_icon_copy.png'>
	      </div>
	      <input name="name" placeholder='用户名' maxlength="16" type='text' autocomplete="off" value=""/>
	        <div class='validation'>
	          <img alt="" src='/static/img/tick.png'>
	        </div>
	    </div>
	    <div class='login_fields__password'>
	      <div class='icon'>
	        <img alt="" src='/static/img/lock_icon_copy.png'>
	      </div>
	      <input name="password" placeholder='密码' maxlength="16" type='text' autocomplete="off">
	      <div class='validation'>
	        <img alt="" src='/static/img/tick.png'>
	      </div>
	    </div>
	    <div class='login_fields__submit'>
	      	<input type='submit' value='确认注册'>
	    </div>
	  </div>
		</form>
	  <div class='success'>
	  </div>
	  <div class='disclaimer'>
	    <p>欢迎</p>
	  </div>
	</div>
	<div class='authent'>
	  <div class="loader" style="height: 44px;width: 44px;margin-left: 28px;">
        <div class="loader-inner ball-clip-rotate-multiple">
            <div></div>
            <div></div>
            <div></div>
        </div>
        </div>
	  <p>认证中...</p>
	</div>
	<div class="OverWindows"></div>

    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src='/static/js/stopExecutionOnTimeout.js?t=1'></script>
    <script type="text/javascript" src="/static/layui/layui.js"></script>
    <script type="text/javascript" src="/static/js/Particleground.js"></script>
    <script type="text/javascript" src="/static/js/Treatment.js"></script>
    <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>

</body>
</html>