gou/Ind/urls.py
from django.conf.urls import url
from Ind import views

urlpatterns = [
    # 首页
    url(r'^home/', views.Home,name='home'),
    # 登录登出注册
    url(r'^log/', views.Login),
    url(r'^logout', views.Loginout),
    url(r'^reg/', views.Register),
    # 购物车
    url(r'^car/', views.Car),
    # 我的
    url(r'^mine/', views.Mine),
    # 闪购
    url(r'^market/$', views.Market, name='ma'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.use_Market, name='market'),
    # 闪购添加删除
    url(r'^add/', views.addshop),
    url(r'^del/', views.delshop),
    # 改变勾选
    url(r'^changecheck/', views.changecheck),
    # 购物车下单
    url(r'^xiadan/', views.order),
    # 购物车下单创建详情
    url(r'^xiandancreate/(\d+)/', views.Ordercreate, name='Ordercreate'),
    # 支付完成
    url(r'^complay/(\d+)/', views.Complay, name='complay'),
    # 跳转代付款
    url(r'^orderwait/', views.OrderWait),
    # 跳转待收货
    url(r'^orderpayed/', views.OrderPayed),
    url(r'^delxiadan/(\d+)', views.Delorder, name='delorder')
]

gou/gou/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from Ind import views
from gou import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ind/', include('Ind.urls', namespace='axf')),
    url(r'^$', views.Home),


]

from django.contrib.staticfiles.urls import static

from gou import settings

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

gou/Ind/models.py
from django.db import models


class Main(models.Model):
    img = models.CharField(max_length=200)  # 图片
    name = models.CharField(max_length=100)  # 名称
    trackid = models.CharField(max_length=16)  # 通用id

    class Meta:
        # 成为父类（抽象化）
        abstract = True


class MainLun(Main):
    # 轮播图
    class Meta:
        db_table = 'index_lun'


class MainDao(Main):
    # 导航
    class Meta:
        db_table = 'index_dao'


class MainMustBuy(Main):
    # 必购物
    class Meta:
        db_table = 'index_mustby'


class MainShop(Main):
    # 商店
    class Meta:
        db_table = 'axf_shop'


class MainShow(Main):
    # 主要展示商品
    categoryid = models.CharField(max_length=16)  # 分类名称
    brandname = models.CharField(max_length=100)  # 分类编号

    img1 = models.CharField(max_length=200)  # 图片
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)

    longname1 = models.CharField(max_length=100)  # 名称
    price1 = models.FloatField(default=0)  # 优惠价格
    marketprice1 = models.FloatField(default=1)  # 原始价格
    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)
    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'


# 闪购（左侧导航栏）
class FoodType(models.Model):
    typeid = models.CharField(max_length=16)  # 分类id（导航栏中根据id显示对应对象）
    typename = models.CharField(max_length=100)  # 类型名称
    childtynames = models.CharField(max_length=200)  # 类型
    tyoesort = models.IntegerField(default=1)  # 排序

    class Meta:
        db_table = 'axf_foodtype'


class Goods(models.Model):
    # 商品展示
    productid = models.CharField(max_length=16)  # 商品编号
    productimg = models.CharField(max_length=200)  # 商品图
    productname = models.CharField(max_length=100)  # 商品名称
    productlongname = models.CharField(max_length=200)  # 商品规格名称
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)  # 商品细节规格
    price = models.FloatField(default=0)  # 折后价格
    marketprice = models.FloatField(default=1)  # 原价
    categoryid = models.CharField(max_length=16)  # 总的分类id
    childcid = models.CharField(max_length=16)  # 子分类id
    childcidname = models.CharField(max_length=100)  # 子名称
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)  # 分类排序（销量。好评度）
    productnum = models.IntegerField(default=1)  # 销量排序

    class Meta:
        db_table = 'axf_goods'


class MinModel(models.Model):
    # 用户
    usernam = models.CharField(max_length=32, unique=True)
    password = models.CharField(max_length=256)
    email = models.CharField(max_length=64, unique=True)
    sex = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='icons')  # 头像图片
    is_delete = models.BooleanField(default=False)  # 是否删除

    class Meta:
        db_table = 'axf_user'


class MineModel(models.Model):
    m = models.OneToOneField(MinModel)
    m_ticket = models.CharField(max_length=225)
    m_time = models.DateTimeField()

    class Meta:
        db_table = 'axf_user_tic'


class CartModel(models.Model):
    # 购物车
    user = models.ForeignKey(MinModel)  # 关联用户
    goods = models.ForeignKey(Goods)  # 管理商品
    c_num = models.IntegerField(default=1)  # 商品个数
    is_select = models.BooleanField(default=True)  # 是否勾选

    class Meta:
        db_table = 'axf_cart'


class OrderModel(models.Model):
    # 订单
    user = models.ForeignKey(MinModel)
    o_num = models.CharField(max_length=64)
    o_status = models.IntegerField(default=0)  # 状态
    o_create = models.DateTimeField(auto_now_add=True)  # 创建时间

    class Meta:
        db_table = 'axf_order'


class OrderGoodsModel(models.Model):
    # 订单和商品的联系
    order = models.ForeignKey(OrderModel)  # 关联订单
    goods = models.ForeignKey(Goods)  # 关联商品
    goods_num = models.IntegerField(default=1)  # 商品个数

    class Meta:
        db_table = 'axf_order_goods'

gou/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">

    <!--订单编号-->
    <a href="/ind/mine/"><button>返回我的</button></a>
    <h3>订单编号:{{ order }}</h3>
    <!--处理结束-->
    <ul>
        {% for o in orders %}
        <!--所有订单信息展示-->
            {{ o.goods.productlongname }}
            <li>
                <!--商品名称展示-->

                <img src="{{ o.goods.productimg }}">
                <span> <!-- 数量展示 -->商品数量：{{ o.goods_num }}</span>
            </li>

        <!--订单处理结束-->

    </ul>
        {% endfor %}
        <!--订单id展示-->
        <a href="{% url 'axf:complay' order %}">
        <button class="btn btn-success btn-block">Alipay</button>
        </a>
    </div>


{% endblock %}

gou/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>
<a href="/ind/mine/"><button>返回我的</button></a>
    {% for i in wait %}
        <!--订单信息展示-->
        <hr style="height: 10px;background-color: red">
        {% for a in i.ordergoodsmodel_set.all %}
            <li>
                <a href=" ">

                    <p><!-- 订单id -->订单编号：{{ i.id }}</p>
                    <p><!-- 数量 -->商品数量：{{ a.goods_num }}</p>
                        <!--展示商品的名称-->
                    <p>商品名称：{{ a.goods.productlongname }}</p>
                        <li>
                            <img src="{{ a.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->

                </a>
            </li>
            {% endfor %}
        <!--订单处理结束-->
    {% endfor %}


{% endblock %}

gou/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>
    <a href="/ind/mine/"><button>返回我的</button></a>
    {% if not wait %}
    <h3>😊没有付款的商品哦😊<br>
        可以去这里看看👉<a href="{% url 'axf:ma' %}">点击我^_^</a></h3>
    {% endif %}
    {% for i in wait %}
    <ul>
        <!--订单信息展示-->
        <hr style="height: 10px;background-color: #5bc0de">
        {% for a in i.ordergoodsmodel_set.all %}
            <li>
                <a href="{% url 'axf:Ordercreate' i.id %}">

                    <p><!-- 订单id -->订单编号：{{ i.id }}</p>
                    <p><!-- 数量 -->商品数量：{{ a.goods_num }}</p>
                        <!--展示商品的名称-->
                    <p>商品名称：{{ a.goods.productlongname }}</p>
                        <li>
                            <img src="{{ a.goods.productimg }}" alt="">
                        </li>
                        <!--处理结束-->

                </a>
            </li>
            {% endfor %}
        <!--订单处理结束-->
        <a href="{% url 'axf:Ordercreate' i.id %}">
        <button class="btn btn-success btn-block">点击支付</button>
        </a>
        <a href="{% url 'axf:delorder' i.id %}">
        <button class="btn btn-success btn-block" style="background-color: red">点击删除</button>
        </a>
    {% endfor %}

    </ul>


{% endblock %}